formulario fale conosco
trainee-solutis/ecommerce pull request #27
Opened 2023-10-25 19:25 UTC by silvaalejesus

2023-10-26 20:17 UTC, 4ntonio19 commented on src/app/components/form/form.component.html
> +        Por favor, insira um name válido.
tem um com name e outro com nome

2023-10-26 20:19 UTC, 4ntonio19 commented on src/app/components/form/form.component.html
> +      <mat-error *ngIf="formulario.get('email')?.errors?.['required'] && formulario.get('email')?.touched">
É bom colocar aquela validação de @email.com, pra n ir um formato errado.

2023-10-27 19:50 UTC, MaateusMDS approved these changes

2023-10-27 19:51 UTC, MaateusMDS requested changes
![image](https://github.com/trainee-solutis/ecommerce/assets/96087111/0b5006d8-161d-4d97-bc2a-6669078bd443)

2023-10-27 20:13 UTC, MaateusMDS approved these changes

2023-10-27 20:14 UTC, merged